---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: test
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: test
          image: "registry.cn-hangzhou.aliyuncs.com/daveroey/cicd:v1.0"
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
