---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      k8s-app: test
  replicas: 2
  template:
    metadata:
      name: test
      creationTimestamp: null
      labels:
        k8s-app: test
    spec:
      containers:
        - name: test
          image: "registry.cn-hangzhou.aliyuncs.com/daveroey/cicd:v1.0"
          ports:
            - name: http
          imagePullPolicy: Always
