apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2021-12-09T07:26:19Z"
  generation: 3
  labels:
    k8s-app: test
  name: test
  namespace: default
  resourceVersion: "725459"
  uid: 4106e7d2-bdc2-47d6-a035-dc9fde26ef50
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: test
      name: test
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/daveroey/cicd:v1.0
        imagePullPolicy: IfNotPresent
        name: test
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-09T07:52:06Z"
    lastUpdateTime: "2021-12-09T07:52:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-09T07:52:06Z"
    lastUpdateTime: "2021-12-09T07:52:07Z"
    message: ReplicaSet "test-85c75697fb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
