
version: "3"
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/daveroey/cicd:v1.0
    ports:
      - 1323:1323
    networks:
      - my-net
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
networks:
  my-net:
