name: Go

on:
  push:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v ./...
    - name: Build Docker Image
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hangzhou.aliyuncs.com'
        namespaces: 'daveroey'
        repository_name: 'cicd'
        user_name: lztaini123
        password: lzt13079120036
        image_version: 'v1.0'
        docker_file: '.'
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.0 # specify kubectl binary version explicitly
        command: apply -f deploy.yaml
