name: Go

on:
  push:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v ./...
    - name: Build Docker Image
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hangzhou.aliyuncs.com'
        namespaces: 'daveroey'
        repository_name: 'cicd'
        user_name: ${{ secrets.REPOSITORY_NAME }}
        password: ${{ secrets.REPOSITORY_PASSWORD }}
        image_version: 'v1.0'
        docker_file: '.'
    - name: scp stack
      uses: garygrossgarten/github-action-scp@release
      with:
        local: docker-stack.yaml
        remote: /data/stack/docker-stack.yaml
        port: ${{ secrets.PORT }}
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        port: ${{ secrets.PORT }}
        script: |-
           docker stack deploy -c /data/stack/docker-stack.yaml go

