name: Go

on:
  push:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v ./...
    - name: Build Docker Image
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hangzhou.aliyuncs.com'
        namespaces: 'daveroey'
        repository_name: 'cicd'
        user_name: ${{ secrets.REPOSITORY_NAME }}
        password: ${{ secrets.REPOSITORY_PASSWORD }}
        image_version: 'v1.0'
        docker_file: '.'
    - name: Deploy to Docker swarm
      uses: Autom3/docker-deployment-action@3.0.1
      with:
        remote_docker_host: root@k9s.fun
        remote_docker_port: 10022
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-swarm
        copy_stack_file: true
        deploy_path: /data/my-deployment
        stack_file_name: docker-stack.yaml
        keep_files: 5
        args: my_applicaion

